version: "3.9"
services:

  api:
    container_name: edtech-api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/test-mm
      - /home/test-mm/node_modules
  db:
    container_name: edtech-db
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}